FROM ruby:2.6.9

RUN bundle config --global frozen 1

WORKDIR /usr/src/app

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt update && apt install -y nodejs && apt remove cmdtest && apt install -y yarn

RUN gem install bundler:2.3.4

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN yarn install

RUN rails db:migrate

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
