# fly.toml app configuration file generated for flix-steven-xu on 2023-06-19T19:08:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flix-steven-xu"
primary_region = "iad"
console_command = "/rails/bin/rails console"
swap_size_mb = 512

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[[vm]]
  size = "shared-cpu-1x"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
